package watch.poe.stats.model.code;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum StatType {
  TIME_API_REPLY_DOWNLOAD,
  TIME_API_TTFB,

  TIME_REPLY_PARSE,
  TIME_REPLY_DESERIALIZE,
  TIME_INDEX_ITEM,
  //  TIME_PERSIST_ENTRY,
  TIME_PROCESS_RIVER,
  TIME_PERSIST_STASHES,
  TIME_MARK_ITEMS_STALE,
  TIME_PERSIST_STASH_ENTRIES,
  TIME_PERSIST_ACCOUNT,
  TIME_PERSIST_CHARACTER,
  TIME_WORKERS_IDLE,

  COUNT_API_ERRORS_READ_TIMEOUT,
  COUNT_API_ERRORS_CONNECT_TIMEOUT,
  COUNT_API_ERRORS_CONN_RESET,
  COUNT_API_ERRORS_5XX,
  COUNT_API_ERRORS_4XX,
  COUNT_API_ERRORS_DUPLICATE,

  COUNT_REPLY_SIZE,
  COUNT_API_CALLS,
  COUNT_TOTAL_STASHES,
  COUNT_TOTAL_ITEMS,
  //  COUNT_ITEMS_DISCARDED_INVALID_LEAGUE,
  COUNT_ACCEPTED_ITEMS,
  COUNT_ACTIVE_ACCOUNTS,

  // todo: discarded total, accepted total

  MISC_APP_STARTUP,
  MISC_APP_SHUTDOWN
}
